name: Deploy Python Azure Function App

on:
  push:
    branches:
      - main
    paths:
      - 'function_app/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Zip Function App contents
        run: |
          cd function_app
          zip -r ../function_app.zip .

      - name: Upload zipped function app as artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: function-app-zip
          path: function_app.zip

      - name: 'Deploy Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: highscore-function-app
          package: ./function_app.zip
